/* eslint-disable */
// Generated by scripts/generate-types.ts. Do not edit manually.

export const GeneratedOpenApiDocument = {
  openapi: '3.0.3',
  info: {
    title: 'Murmura API',
    version: '0.1.0'
  },
  paths: {}
} as const;

export const GeneratedApiOperations = [] as const;

export type GeneratedApiOperation = (typeof GeneratedApiOperations)[number];
export type GeneratedApiPath = never;
export type GeneratedApiMethod = never;
