import fs from 'node:fs/promises';
import path from 'node:path';
import { buildServer } from '../packages/cognitive-core/api/src/server.js';

type OpenApiDocument = {
  openapi?: string;
  info?: { title?: string; version?: string };
  paths?: Record<string, Record<string, Record<string, unknown>>>;
};

function toTypeName(input: string) {
  return input
    .replace(/[{}]/g, '')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function createGeneratedTypes(document: OpenApiDocument) {
  const paths = document.paths ?? {};
  const operations = Object.entries(paths).flatMap(([routePath, methods]) =>
    Object.entries(methods).map(([method, operation]) => ({
      method: method.toUpperCase(),
      routePath,
      operationId:
        typeof operation['operationId'] === 'string'
          ? operation['operationId']
          : `${method}${toTypeName(routePath)}`,
      tags: Array.isArray(operation['tags']) ? operation['tags'] : [],
      hasRequestBody: Boolean(operation['requestBody']),
      responses:
        operation['responses'] && typeof operation['responses'] === 'object'
          ? Object.keys(operation['responses'] as Record<string, unknown>)
          : []
    }))
  );

  return `/* eslint-disable */
// Generated by scripts/generate-types.ts. Do not edit manually.

export const GeneratedOpenApiDocument = ${JSON.stringify(document, null, 2)} as const;

export const GeneratedApiOperations = ${JSON.stringify(operations, null, 2)} as const;

export type GeneratedApiOperation = (typeof GeneratedApiOperations)[number];
export type GeneratedApiPath = (typeof GeneratedApiOperations)[number]['routePath'];
export type GeneratedApiMethod = (typeof GeneratedApiOperations)[number]['method'];
`;
}

async function main() {
  const app = buildServer();

  try {
    await app.ready();
    const document = app.swagger() as OpenApiDocument;

    const openApiDir = path.resolve('packages', 'shared-types', 'openapi');
    const generatedPath = path.resolve('packages', 'shared-types', 'src', 'api', 'generated.ts');
    const specPath = path.join(openApiDir, 'openapi.json');

    await fs.mkdir(openApiDir, { recursive: true });
    await fs.writeFile(specPath, JSON.stringify(document, null, 2), 'utf8');
    await fs.writeFile(generatedPath, createGeneratedTypes(document), 'utf8');

    console.log(`OpenAPI spec written to ${specPath}`);
    console.log(`Shared types synchronized at ${generatedPath}`);
  } finally {
    await app.close();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
